dubbo:
  application:
    name: center-web
  registry:
    protocol: zookeeper
    address: 10.36.8.8:2181
server:
  port: 9090

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 10.36.8.8:22122

image:
  server: http://10.36.8.8/

